# Dependencies
FROM node:22-alpine as deps

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

# Builder 
FROM node:22-alpine as build

WORKDIR /usr/src/app

# Copy dependencies from deps stage
COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copy source code
COPY . .

RUN npx prisma generate

RUN npm run build

RUN npm prune --omit=dev && npm cache clean --force

# Create final image
FROM node:22-alpine as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

# Copy dist folder
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/prisma ./prisma

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD ["node", "dist/src/main.js"]